version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
    groups:
      linter:
        patterns:
        - "eslint*"
        - "@typescript-eslint*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
